version: '3.8'
services:
    redis_db:
        image: "redis"
        ports:
            - "6389:6379"
        expose:
            - 6379
        restart: always
    api:
        container_name: beave-cms
        build:
            context: ./
            dockerfile: Dockerfile.dev
            target: dev
        volumes:
            - .:/app
        command: sh -c "npm i && npm run dev"
        ports:
            - "${PORT}:1380"
        environment:
            NODE_ENV: development
            DEBUG: nodejs-docker-express:*
