FROM node:lts-alpine3.15 as base

WORKDIR /app
COPY . .
COPY package*.json ./
# COPY package-lock.json ./
EXPOSE 8080

FROM base as production
ENV NODE_ENV=production
RUN npm ci --only=production
CMD ["npm", "start"]

FROM base as dev
ENV NODE_ENV=development
# timezone env with default
ENV TZ="Asia/Dubai"
RUN apk add --no-cache python3 make g++
# RUN apk add --no-cache  chromium --repository=http://dl-cdn.alpinelinux.org/alpine/v3.10/main
RUN npm install
# RUN npm install -g nodemon
# CMD sh -c 'npm install && npm run dev'
CMD ["npm", "run", "dev"]