version: '3.8'
services:
  api:
    container_name: landmark-leisure-cms
    build:
      context: ./
      dockerfile: Dockerfile.dev
      target: dev
    volumes:
      - .:/app
    command: sh -c "npm i && npm run dev"
    ports:
      - "8400:8080"
    environment:
      NODE_ENV: development
      DEBUG: nodejs-docker-express:*
